### ISSUE TITLE
Colab gin version 0.5.0 not working

### ISSUE THREAD

**Issue by karimkalimu** [magenta/ddsp#428]
Hello, 

gin-config version=0.3.0 and 0.4.0 worked with me, but 0.5.0 raised an error

`TypeError                                 Traceback (most recent call last)
[<ipython-input-1-6fd98db16ce5>](https://localhost:8080/#) in <module>()
      6 import tensorflow as tf
      7 
----> 8 import ddsp.training
      9 from ddsp.colab import colab_utils
     10 from ddsp.colab.colab_utils import play, specplot
2 frames
[/usr/local/lib/python3.7/dist-packages/ddsp/dags.py](https://localhost:8080/#) in DAGLayer()
    132     return self.run_dag(inputs, **kwargs)
    133 
--> 134   @gin.configurable(whitelist=['verbose'])  # For debugging.
    135   def run_dag(self,
    136               inputs: TensorDict,
TypeError: configurable() got an unexpected keyword argument 'whitelist'`

thanks for the cool library

**Comment by karimkalimu** [comment]
sorry, I was using an older version experimenting with this [project](https://github.com/juanalonso/DDSP-singing-experiments)

I will close the issue
